# Generated by Django 5.1.12 on 2026-01-04 04:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShooterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uspsa_number', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('club', models.CharField(blank=True, max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassifierAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('hit_factor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('raw_percent', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), editable=False, max_digits=7)),
                ('capped_percent', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), editable=False, max_digits=7)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('CSV', 'CSV'), ('PRACTISCORE', 'PractiScore')], default='MANUAL', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='classification.classifierstage')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='classification.division')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='classification.shooterprofile')),
            ],
            options={
                'ordering': ['-match_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HHF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hhf', models.DecimalField(decimal_places=4, max_digits=10)),
                ('effective_date', models.DateField()),
                ('source', models.TextField(blank=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hhfs', to='classification.division')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hhfs', to='classification.classifierstage')),
            ],
            options={
                'ordering': ['-effective_date'],
                'unique_together': {('stage', 'division', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='DivisionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('implied_class', models.CharField(default='Unclassified', max_length=8)),
                ('highest_badge', models.CharField(default='Unclassified', max_length=8)),
                ('active_scores', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='classification.division')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_summaries', to='classification.shooterprofile')),
            ],
            options={
                'unique_together': {('profile', 'division')},
            },
        ),
        migrations.CreateModel(
            name='DailyAggregateScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('sda_percent', models.DecimalField(decimal_places=4, max_digits=7)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('is_mro', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to='classification.classifierstage')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to='classification.division')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to='classification.shooterprofile')),
            ],
            options={
                'ordering': ['-match_date'],
                'unique_together': {('profile', 'division', 'stage', 'match_date')},
            },
        ),
    ]
