# Generated by Django 5.1.12 on 2026-01-04 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('practiscore_club_url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('fetch_frequency_minutes', models.PositiveIntegerField(default=60)),
                ('user_agent', models.CharField(default='ClassifierTrackerBot/1.0', max_length=256)),
                ('max_requests_per_hour', models.PositiveIntegerField(default=30)),
                ('allowed_domains', models.CharField(default='practiscore.com', max_length=256)),
                ('parsing_mode', models.CharField(choices=[('AUTO', 'Auto'), ('HTML_V1', 'HTML v1'), ('HTML_V2', 'HTML v2')], default='AUTO', max_length=16)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('matches_checked', models.IntegerField(default=0)),
                ('scores_found', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=32)),
                ('log', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practiscore_match_url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('OK', 'OK'), ('NO_CHANGE', 'No change'), ('FAILED', 'Failed'), ('ACCESS_DENIED', 'Access denied'), ('PARSE_ERROR', 'Parse error')], default='OK', max_length=32)),
                ('last_error', models.TextField(blank=True)),
                ('etag', models.CharField(blank=True, max_length=128)),
                ('last_modified', models.CharField(blank=True, max_length=128)),
                ('club_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='collector.clubsource')),
            ],
        ),
        migrations.CreateModel(
            name='CollectedScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.TextField()),
                ('competitor_uspsa_number', models.TextField(blank=True, null=True)),
                ('division', models.CharField(max_length=32)),
                ('classifier_code', models.CharField(max_length=16)),
                ('match_date', models.DateField()),
                ('hit_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('raw_excerpt', models.TextField(blank=True)),
                ('import_status', models.CharField(choices=[('NEW', 'New'), ('DUPLICATE', 'Duplicate'), ('IMPORTED', 'Imported'), ('REJECTED', 'Rejected')], default='NEW', max_length=16)),
                ('mapped_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.shooterprofile')),
                ('match_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='collector.matchsource')),
            ],
        ),
        migrations.CreateModel(
            name='ClubManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('club_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.clubsource')),
            ],
            options={
                'unique_together': {('user', 'club_source')},
            },
        ),
    ]
